apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vprodb-allow-vproapp-ingress
  namespace: vprofile
spec:
  podSelector:
    matchLabels:
      app: vprodb
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: vproapp
    ports:
    - protocol: TCP
      port: 3306