apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vpromq-allow-app
  namespace: vprofile
spec:
  podSelector:
    matchLabels:
      app: vpromq
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: vproapp
    ports:
    - protocol: TCP
      port: 5672